apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: payment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure resources for payment apps
  roles:
    - name: read-only
      description: Read Only Access
      policies:
        - p, proj:payment:read-only, applications, get, *, allow
    - name: read-write
      description: Read Write Access
      policies:
        - p, proj:payment:read-write, applications, get, *, allow
        - p, proj:payment:read-write, applications, sync, *, allow
        - p, proj:payment:read-write, applications, update, *, allow
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  sourceRepos:
    - https://github.com/orathaipp/nonprod-k8s-manifests.git
    - git@github.com:orathaipp/nonprod-k8s-manifests.git
