apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  description: Infrastructure resources
  roles:
    - name: read-write
      description: Full access (for nongkai)
      policies:
        - p, proj:cart:read-write, applications, get, *, allow
        - p, proj:cart:read-write, applications, create, *, allow
        - p, proj:cart:read-write, applications, update, *, allow
        - p, proj:cart:read-write, applications, delete, *, allow
        - p, proj:cart:read-write, applications, sync, *, allow
    - name: read-only
      description: Read-only access (for nongped)
      policies:
        - p, proj:cart:read-only, applications, get, *, allow
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'  
  sourceRepos:
    - https://github.com/orathaipp/nonprod-k8s-manifests.git
